### ISSUE TITLE
Add Plato?

### ISSUE THREAD

**Issue by OBoudreaux** [Rlshep/BJCPBeerStyles_Android#20]
This reference tool would be even more useful if the user had the option to toggle the gravity numbers to Plato.

**Comment by Rlshep** [comment]
Thanks for feedback. I'm working on internationalization. I will add that to the list.

**Comment by OBoudreaux** [comment]
Thanks for making the app!

**Comment by LondonRain** [comment]
...same goes for SRM to EBC conversion.

**Comment by Rlshep** [comment]
Metric units are added with latest change in beta. Please, sign up and leave feedback.

**Comment by OBoudreaux** [comment]
Top notch! Thanks.

**Comment by Rlshep** [comment]
Added with version 1.2.1
