### ISSUE TITLE
Going back from a category does not preserve the last view

### ISSUE THREAD

**Issue by LondonRain** [Rlshep/BJCPBeerStyles_Android#24]
Steps to reproduce:
* Start the app
* Scroll down to category 24 - Belgian ale
* click on it
* press the back button
* it scrolls up to show the first categories

I would expect it to keep the viewport as it was before and leave it to the user if he wants to scroll up or go on selecting another category near the last one.

**Comment by Rlshep** [comment]
If you use the standard android back button, you get the desired effect. I know it is confusing to have the two buttons act different, but I like it like that and probably won't change.

**Comment by LondonRain** [comment]
It does not make a difference whether I use the arrow button the app provides or the hardware android back button. It always jumps back to the top of the list.

**Comment by Rlshep** [comment]
I see what you mean.

**Comment by Rlshep** [comment]
Change now in Beta version 1.2.5
